//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Contact {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Contact() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiLanguage.Resources.Views.Contact.Contact", typeof(Contact).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазини.
        /// </summary>
        public static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to гр. София, Коста Лулчев 52, Скай Сити Мол.
        /// </summary>
        public static string StoreAddress {
            get {
                return ResourceManager.GetString("StoreAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to гр. Габрово бул. Априлов 40 МОЛ Габрово.
        /// </summary>
        public static string StoreAddress1 {
            get {
                return ResourceManager.GetString("StoreAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to гр. Русе, ул. Петко Каравелов 15, VIP Center.
        /// </summary>
        public static string StoreAddress2 {
            get {
                return ResourceManager.GetString("StoreAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to гр. Русе, ул. Александровска 62.
        /// </summary>
        public static string StoreAddress3 {
            get {
                return ResourceManager.GetString("StoreAddress3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to гр. Русе, бул. Липник, МОЛ Русе.
        /// </summary>
        public static string StoreAddress4 {
            get {
                return ResourceManager.GetString("StoreAddress4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Радианна Голд София.
        /// </summary>
        public static string StoreCaption {
            get {
                return ResourceManager.GetString("StoreCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Радианна Голд Бургас.
        /// </summary>
        public static string StoreCaption1 {
            get {
                return ResourceManager.GetString("StoreCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Радианна Голд Русе 1.
        /// </summary>
        public static string StoreCaption2 {
            get {
                return ResourceManager.GetString("StoreCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Радианна Голд Русе 2.
        /// </summary>
        public static string StoreCaption3 {
            get {
                return ResourceManager.GetString("StoreCaption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Радианна Голд Русе 3.
        /// </summary>
        public static string StoreCaption4 {
            get {
                return ResourceManager.GetString("StoreCaption4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StoreDescription {
            get {
                return ResourceManager.GetString("StoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазин за бижута, часовници и сребърни икони..
        /// </summary>
        public static string StoreDescription1 {
            get {
                return ResourceManager.GetString("StoreDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Магазин за златна и сребърна бижутерия, часовници, стоманена бижутерия, сувенири, подаръци и сребърни икони..
        /// </summary>
        public static string StoreDescription2 {
            get {
                return ResourceManager.GetString("StoreDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StoreDescription3 {
            get {
                return ResourceManager.GetString("StoreDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string StoreDescription4 {
            get {
                return ResourceManager.GetString("StoreDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radiannagold@abv.bg.
        /// </summary>
        public static string StoreEmail {
            get {
                return ResourceManager.GetString("StoreEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radiannagold@abv.bg.
        /// </summary>
        public static string StoreEmail1 {
            get {
                return ResourceManager.GetString("StoreEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radiannagold@abv.bg.
        /// </summary>
        public static string StoreEmail2 {
            get {
                return ResourceManager.GetString("StoreEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radiannagold@abv.bg.
        /// </summary>
        public static string StoreEmail3 {
            get {
                return ResourceManager.GetString("StoreEmail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radiannagold@abv.bg.
        /// </summary>
        public static string StoreEmail4 {
            get {
                return ResourceManager.GetString("StoreEmail4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0896780278 / 0896780288.
        /// </summary>
        public static string StorePhone {
            get {
                return ResourceManager.GetString("StorePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0896780278 / 0896780288.
        /// </summary>
        public static string StorePhone1 {
            get {
                return ResourceManager.GetString("StorePhone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0896780278 / 0896780288.
        /// </summary>
        public static string StorePhone2 {
            get {
                return ResourceManager.GetString("StorePhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0896780278 / 0896780288.
        /// </summary>
        public static string StorePhone3 {
            get {
                return ResourceManager.GetString("StorePhone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0896780278 / 0896780288.
        /// </summary>
        public static string StorePhone4 {
            get {
                return ResourceManager.GetString("StorePhone4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to събота – неделя: 10.00 – 19.00ч..
        /// </summary>
        public static string StoreWeekendHours {
            get {
                return ResourceManager.GetString("StoreWeekendHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to събота – неделя: 10.00 – 19.00ч..
        /// </summary>
        public static string StoreWeekendHours1 {
            get {
                return ResourceManager.GetString("StoreWeekendHours1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to събота – неделя: 10.00 – 19.00ч..
        /// </summary>
        public static string StoreWeekendHours2 {
            get {
                return ResourceManager.GetString("StoreWeekendHours2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to събота – неделя: 10.00 – 19.00ч..
        /// </summary>
        public static string StoreWeekendHours3 {
            get {
                return ResourceManager.GetString("StoreWeekendHours3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to събота – неделя: 10.00 – 19.00ч..
        /// </summary>
        public static string StoreWeekendHours4 {
            get {
                return ResourceManager.GetString("StoreWeekendHours4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to понеделник – петък: 10.00 – 20.00 ч..
        /// </summary>
        public static string StoreWorkWeekHours {
            get {
                return ResourceManager.GetString("StoreWorkWeekHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to понеделник – петък: 10.00 – 20.00 ч..
        /// </summary>
        public static string StoreWorkWeekHours1 {
            get {
                return ResourceManager.GetString("StoreWorkWeekHours1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to понеделник – петък: 10.00 – 20.00 ч..
        /// </summary>
        public static string StoreWorkWeekHours2 {
            get {
                return ResourceManager.GetString("StoreWorkWeekHours2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to понеделник – петък: 10.00 – 20.00 ч..
        /// </summary>
        public static string StoreWorkWeekHours3 {
            get {
                return ResourceManager.GetString("StoreWorkWeekHours3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to понеделник – петък: 10.00 – 20.00 ч..
        /// </summary>
        public static string StoreWorkWeekHours4 {
            get {
                return ResourceManager.GetString("StoreWorkWeekHours4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свържете се с нас.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
